### ISSUE TITLE
Internal error for DRBOperationTree

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoapods.org#143]
https://cocoapods.org/pods/DRBOperationTree

hrm?

**Comment by skyylex** [comment]
Same for the https://cocoapods.org/pods/TouchXML

**Comment by segiddins** [comment]
```
2015-05-04T20:47:09.901947+00:00 app[web.1]: TypeError - no implicit conversion of nil into String:
2015-05-04T20:47:09.901951+00:00 app[web.1]: 	/app/views/pod.slim:17:in `+'
2015-05-04T20:47:09.901953+00:00 app[web.1]: 	/app/views/pod.slim:17:in `block in singleton class'
2015-05-04T20:47:09.901954+00:00 app[web.1]: 	/app/views/pod.slim:-1:in `instance_eval'
2015-05-04T20:47:09.901956+00:00 app[web.1]: 	/app/views/pod.slim:-1:in `singleton class'
2015-05-04T20:47:09.901957+00:00 app[web.1]: 	/app/views/pod.slim:-3:in `__tilt_70156534788920'
2015-05-04T20:47:09.901959+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
2015-05-04T20:47:09.901960+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
2015-05-04T20:47:09.901962+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
2015-05-04T20:47:09.901963+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:814:in `render'
2015-05-04T20:47:09.901964+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:742:in `slim'
2015-05-04T20:47:09.901966+00:00 app[web.1]: 	/app/app.rb:95:in `pod_page_for_result'
2015-05-04T20:47:09.901967+00:00 app[web.1]: 	/app/app.rb:65:in `block in <class:App>'
2015-05-04T20:47:09.901969+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
2015-05-04T20:47:09.901970+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
2015-05-04T20:47:09.901971+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
2015-05-04T20:47:09.901973+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
2015-05-04T20:47:09.901974+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
2015-05-04T20:47:09.901976+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
2015-05-04T20:47:09.901977+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
2015-05-04T20:47:09.901978+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
2015-05-04T20:47:09.901980+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
2015-05-04T20:47:09.901981+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
2015-05-04T20:47:09.901982+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
2015-05-04T20:47:09.901983+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
2015-05-04T20:47:09.901985+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
2015-05-04T20:47:09.901986+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
2015-05-04T20:47:09.901987+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
2015-05-04T20:47:09.901988+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
2015-05-04T20:47:09.901990+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
2015-05-04T20:47:09.901991+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
2015-05-04T20:47:09.901992+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
2015-05-04T20:47:09.901994+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
2015-05-04T20:47:09.901995+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
2015-05-04T20:47:09.901996+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
2015-05-04T20:47:09.901998+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
2015-05-04T20:47:09.901999+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/deflater.rb:25:in `call'
2015-05-04T20:47:09.902000+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
2015-05-04T20:47:09.902001+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
2015-05-04T20:47:09.902002+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
2015-05-04T20:47:09.902004+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
2015-05-04T20:47:09.902005+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
2015-05-04T20:47:09.902006+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
2015-05-04T20:47:09.902007+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'
2015-05-04T20:47:09.902009+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
2015-05-04T20:47:09.902010+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
2015-05-04T20:47:09.902011+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
2015-05-04T20:47:09.902012+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
2015-05-04T20:47:09.902019+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
2015-05-04T20:47:09.902020+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
2015-05-04T20:47:09.902022+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/connection.rb:86:in `block in pre_process'
2015-05-04T20:47:09.902023+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/connection.rb:84:in `catch'
2015-05-04T20:47:09.902024+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/connection.rb:84:in `pre_process'
2015-05-04T20:47:09.902025+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/connection.rb:53:in `process'
2015-05-04T20:47:09.902026+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/connection.rb:39:in `receive_data'
2015-05-04T20:47:09.902028+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
2015-05-04T20:47:09.902029+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
2015-05-04T20:47:09.902030+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/backends/base.rb:73:in `start'
2015-05-04T20:47:09.902032+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/server.rb:162:in `start'
2015-05-04T20:47:09.902033+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/controllers/controller.rb:87:in `start'
2015-05-04T20:47:09.902034+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/runner.rb:199:in `run_command'
2015-05-04T20:47:09.902035+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/runner.rb:155:in `run!'
2015-05-04T20:47:09.902037+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/bin/thin:6:in `<top (required)>'
2015-05-04T20:47:09.902038+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/bin/thin:23:in `load'
2015-05-04T20:47:09.902039+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/bin/thin:23:in `<main>'
```

**Comment by orta** [comment]
Got this, the same pod had been modified multiple times, and the first one was un-parsable
