### ISSUE TITLE
My Pod showing Internal Server Error 500

### ISSUE THREAD

**Issue by alokjha** [CocoaPods/cocoapods.org#256]
When trying to open my pod [GetSimpl-iOS7](http://cocoapods.org/pods/GetSimpl-iOS7) I am getting 
Internal Server Error 500 . This has been going for at least 3-4 days. 
[This may help](https://github.com/CocoaPods/CocoaPods/issues/4922) in solving it.

**Comment by orta** [comment]
Interesting,

```
2016-02-23T19:34:50.419974+00:00 app[web.1]: NoMethodError - undefined method `specification_data' for nil:NilClass:
2016-02-23T19:34:50.419979+00:00 app[web.1]: 	/app/app.rb:167:in `pod_page_for_result'
2016-02-23T19:34:50.419984+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
2016-02-23T19:34:50.419985+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
2016-02-23T19:34:50.419983+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
2016-02-23T19:34:50.419986+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
2016-02-23T19:34:50.419980+00:00 app[web.1]: 	/app/app.rb:96:in `block in <class:App>'
2016-02-23T19:34:50.419988+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
2016-02-23T19:34:50.419988+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
2016-02-23T19:34:50.419990+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
2016-02-23T19:34:50.419991+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
2016-02-23T19:34:50.419990+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
2016-02-23T19:34:50.419992+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
2016-02-23T19:34:50.419986+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
2016-02-23T19:34:50.419993+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
2016-02-23T19:34:50.419984+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
2016-02-23T19:34:50.419993+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
2016-02-23T19:34:50.419995+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
2016-02-23T19:34:50.419995+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
2016-02-23T19:34:50.419994+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
2016-02-23T19:34:50.419997+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
2016-02-23T19:34:50.419996+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
2016-02-23T19:34:50.419997+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
2016-02-23T19:34:50.419998+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
2016-02-23T19:34:50.419999+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
2016-02-23T19:34:50.420001+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
2016-02-23T19:34:50.419999+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/deflater.rb:25:in `call'
2016-02-23T19:34:50.419987+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
2016-02-23T19:34:50.420002+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
2016-02-23T19:34:50.420003+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
2016-02-23T19:34:50.420003+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'
2016-02-23T19:34:50.420001+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
2016-02-23T19:34:50.420006+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
2016-02-23T19:34:50.420004+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
2016-02-23T19:34:50.420008+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-attack-4.3.0/lib/rack/attack.rb:104:in `call'
2016-02-23T19:34:50.420006+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
2016-02-23T19:34:50.420022+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/connection.rb:39:in `receive_data'
2016-02-23T19:34:50.419989+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
2016-02-23T19:34:50.420011+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/connection.rb:53:in `process'
2016-02-23T19:34:50.420005+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
2016-02-23T19:34:50.420028+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/runner.rb:155:in `run!'
2016-02-23T19:34:50.420027+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/controllers/controller.rb:87:in `start'
2016-02-23T19:34:50.420007+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
2016-02-23T19:34:50.420027+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/runner.rb:199:in `run_command'
2016-02-23T19:34:50.420000+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
2016-02-23T19:34:50.420029+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/bin/thin:23:in `load'
2016-02-23T19:34:50.420029+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/bin/thin:6:in `<top (required)>'
2016-02-23T19:34:50.420025+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
2016-02-23T19:34:50.420005+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
2016-02-23T19:34:50.420009+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/connection.rb:86:in `block in pre_process'
2016-02-23T19:34:50.420030+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/bin/thin:23:in `<main>'
2016-02-23T19:34:50.420025+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/backends/base.rb:73:in `start'
2016-02-23T19:34:50.420026+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/server.rb:162:in `start'
2016-02-23T19:34:50.420009+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/connection.rb:84:in `catch'
2016-02-23T19:34:50.420010+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/connection.rb:84:in `pre_process'
2016-02-23T19:34:50.420024+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
```

**Comment by alokjha** [comment]
So if I push a new version of pod , will it fix the issue ?

**Comment by orta** [comment]
It might, it's worth a look, I don't have too much spare time ATM to delve into this

**Comment by alokjha** [comment]
So pushing a new release fixed the issue . Wonder why was the issue in the first place itself.
