### ISSUE TITLE
Internal Server Error (500) on our pod page

### ISSUE THREAD

**Issue by jeremybdk** [CocoaPods/cocoapods.org#281]
Hello,

Since our last pod update, our page on Cocoapods is now broken: https://cocoapods.org/pods/OTAppaloosa

How can we help you fix this ?

Thanks !

**Comment by orta** [comment]
This looks like a side-effect of whatever happened here: https://groups.google.com/forum/#!topic/cocoapods/SJNu1FoY1IM

CocoaDocs is fine with it - http://cocoadocs.org/docsets/OTAppaloosa/0.5.9/

**Comment by orta** [comment]
```
2016-06-28T12:31:35.408166+00:00 app[web.1]: NoMethodError - undefined method `specification_data' for nil:NilClass:
2016-06-28T12:31:35.408187+00:00 app[web.1]: 	/app/app.rb:167:in `pod_page_for_result'
2016-06-28T12:31:35.408195+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
2016-06-28T12:31:35.408190+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
2016-06-28T12:31:35.408192+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
2016-06-28T12:31:35.408192+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
2016-06-28T12:31:35.408193+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
2016-06-28T12:31:35.408194+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
2016-06-28T12:31:35.408189+00:00 app[web.1]: 	/app/app.rb:96:in `block in <class:App>'
2016-06-28T12:31:35.408195+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
2016-06-28T12:31:35.408198+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
2016-06-28T12:31:35.408205+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
```

Looks like GitHub may have said the commit succeeded, but that we couldn't get it into the db?

**Comment by orta** [comment]
Yeah, after marking the `0.6.0` - `pod_version` as `deleted`, the page works again. http://cocoapods.org/pods/OTAppaloosa/


We're not seeing a podspec in the repo either: https://github.com/CocoaPods/Specs/tree/master/Specs/OTAppaloosa

**Comment by orta** [comment]
@alloy in Trunk do we write to the db about a version before we've got confirmation on a commit?

**Comment by alloy** [comment]
We _should_ be writing to the DB in a transaction and commit the transaction if no errors occur during e.g. pushing to GitHub.

**Comment by orta** [comment]
This is fixed now, assumably by pushing another version, I've not had reports of this again so far
